# This file configures the controllers for the Eyou robot.

controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # Controller for the left arm
    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # Controller for the right arm
    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # Controller for the grippers (using a simpler controller)
    #left_gripper_controller:
    #  type: position_controllers/GripperActionController

    #right_gripper_controller:
    #  type: position_controllers/GripperActionController

    # Broadcaster for joint states
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# Parameters for the left arm controller
left_arm_controller:
  ros__parameters:
    joints:
      - left_arm_joint_1
      - left_arm_joint_2
      - left_arm_joint_3
      - left_arm_joint_4
      - left_arm_joint_5
      - left_arm_joint_6
      - left_arm_joint_7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

# Parameters for the right arm controller
right_arm_controller:
  ros__parameters:
    joints:
      - right_arm_joint_1
      - right_arm_joint_2
      - right_arm_joint_3
      - right_arm_joint_4
      - right_arm_joint_5
      - right_arm_joint_6
      - right_arm_joint_7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

# Parameters for the left gripper controller
left_gripper_controller:
  ros__parameters:
    joint: left_gripper_joint

# Parameters for the right gripper controller
right_gripper_controller:
  ros__parameters:
    joint: right_gripper_joint
